// <auto-generated />
using System;
using DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(GolestanTestDbContext))]
    [Migration("20221114074010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.RetailStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTell")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParenetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParenetId");

                    b.ToTable("RetailStores");
                });

            modelBuilder.Entity("DataAccess.Models.WorkStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RetailStoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RetailStoreId");

                    b.ToTable("WorkStations");
                });

            modelBuilder.Entity("DataAccess.Models.RetailStore", b =>
                {
                    b.HasOne("DataAccess.Models.RetailStore", "Parenet")
                        .WithMany("InverseParenet")
                        .HasForeignKey("ParenetId");

                    b.Navigation("Parenet");
                });

            modelBuilder.Entity("DataAccess.Models.WorkStation", b =>
                {
                    b.HasOne("DataAccess.Models.RetailStore", "RetailStore")
                        .WithMany("WorkStations")
                        .HasForeignKey("RetailStoreId");

                    b.Navigation("RetailStore");
                });

            modelBuilder.Entity("DataAccess.Models.RetailStore", b =>
                {
                    b.Navigation("InverseParenet");

                    b.Navigation("WorkStations");
                });
#pragma warning restore 612, 618
        }
    }
}
